services:
    _defaults:
        public: true

    CoreShop\Bundle\PayumBundle\Extension\UpdatePaymentStateExtension:
        arguments:
            - '@coreshop.state_machine_manager'
        tags:
            - { name: payum.extension, all: true, prepend: true }

    CoreShop\Bundle\PayumBundle\Extension\UpdateOrderStateExtension:
        arguments:
            - '@coreshop.state_machine_manager'
        tags:
            - { name: payum.extension, all: true, prepend: true }
